import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { FileText, Target, Users, Calendar, AlertCircle } from 'lucide-react'

interface CharterViewProps {
  content: any
  showBranding?: boolean
  brandingText?: string
}

export function CharterView({ content, showBranding = true, brandingText = "Generated by Project Genie" }: CharterViewProps) {
  if (!content) return null

  return (
    <div className="space-y-6 p-6 bg-white rounded-lg">
      {/* Header */}
      <div className="text-center space-y-2">
        <div className="flex justify-center mb-4">
          <FileText className="h-12 w-12 text-blue-600" />
        </div>
        <h1 className="text-3xl font-bold">Project Charter</h1>
        <p className="text-gray-600">Official Project Authorization Document</p>
      </div>

      <Separator />

      {/* Project Overview */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Target className="h-5 w-5" />
            Project Overview
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h3 className="font-semibold mb-2">Project Background</h3>
            <p className="text-gray-700">{content.projectBackground || 'Strategic initiative aligned with organizational goals.'}</p>
          </div>
          
          <div>
            <h3 className="font-semibold mb-2">Vision Statement</h3>
            <p className="text-gray-700">{content.vision || 'To deliver exceptional value through innovative solutions.'}</p>
          </div>
        </CardContent>
      </Card>

      {/* Project Definition */}
      <Card>
        <CardHeader>
          <CardTitle>Project Definition</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h3 className="font-semibold mb-2">Objectives</h3>
            <ul className="list-disc pl-5 space-y-1">
              {(content.projectDefinition?.objectives || [
                'Deliver project on time and within budget',
                'Meet all specified requirements',
                'Achieve quality standards'
              ]).map((obj: string, idx: number) => (
                <li key={idx} className="text-gray-700">{obj}</li>
              ))}
            </ul>
          </div>

          <div>
            <h3 className="font-semibold mb-2">Scope</h3>
            <p className="text-gray-700">{content.projectDefinition?.scope || 'All defined project deliverables as per requirements.'}</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">Key Deliverables</h3>
            <ul className="list-disc pl-5 space-y-1">
              {(content.projectDefinition?.deliverables || [
                'Project documentation',
                'Implementation deliverables',
                'Training materials'
              ]).map((del: string, idx: number) => (
                <li key={idx} className="text-gray-700">{del}</li>
              ))}
            </ul>
          </div>

          {content.projectDefinition?.exclusions && (
            <div>
              <h3 className="font-semibold mb-2">Exclusions</h3>
              <ul className="list-disc pl-5 space-y-1">
                {content.projectDefinition.exclusions.map((exc: string, idx: number) => (
                  <li key={idx} className="text-gray-700">{exc}</li>
                ))}
              </ul>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Business Case */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <AlertCircle className="h-5 w-5" />
            Business Case
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h3 className="font-semibold mb-2">Reasons for Project</h3>
            <p className="text-gray-700">{content.businessCase?.reasons || 'Strategic alignment with organizational objectives.'}</p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">Expected Benefits</h3>
            <ul className="list-disc pl-5 space-y-1">
              {(content.businessCase?.benefits || [
                'Improved operational efficiency',
                'Cost reduction',
                'Enhanced capabilities'
              ]).map((benefit: string, idx: number) => (
                <li key={idx} className="text-gray-700">{benefit}</li>
              ))}
            </ul>
          </div>

          <div>
            <h3 className="font-semibold mb-2">Key Risks</h3>
            <ul className="list-disc pl-5 space-y-1">
              {(content.businessCase?.risks || [
                'Timeline constraints',
                'Resource availability',
                'Technical complexity'
              ]).map((risk: string, idx: number) => (
                <li key={idx} className="text-gray-700">{risk}</li>
              ))}
            </ul>
          </div>

          {content.businessCase?.costBenefit && (
            <div>
              <h3 className="font-semibold mb-2">Cost-Benefit Analysis</h3>
              <p className="text-gray-700">{content.businessCase.costBenefit}</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Stakeholders */}
      {content.stakeholders && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Users className="h-5 w-5" />
              Key Stakeholders
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {content.stakeholders.map((stakeholder: any, idx: number) => (
                <div key={idx} className="border rounded-lg p-3">
                  <p className="font-semibold">{stakeholder.role}</p>
                  <p className="text-sm text-gray-600">{stakeholder.responsibilities}</p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Timeline */}
      {content.timeline && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="h-5 w-5" />
              Project Timeline
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {content.timeline.milestones?.map((milestone: any, idx: number) => (
                <div key={idx} className="flex justify-between items-center p-3 bg-gray-50 rounded">
                  <div>
                    <p className="font-semibold">{milestone.name}</p>
                    <p className="text-sm text-gray-600">{milestone.description}</p>
                  </div>
                  <Badge variant="outline">{milestone.date}</Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Approval Section */}
      <Card>
        <CardHeader>
          <CardTitle>Approval</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <p className="text-sm text-gray-600">Project Sponsor</p>
                <div className="border-b-2 border-gray-300 mt-8 mb-2"></div>
                <p className="text-sm">Signature & Date</p>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <p className="text-sm text-gray-600">Project Manager</p>
                <div className="border-b-2 border-gray-300 mt-8 mb-2"></div>
                <p className="text-sm">Signature & Date</p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Branding Footer */}
      {showBranding && (
        <div className="text-center pt-6 border-t">
          <p className="text-sm text-gray-500">{brandingText}</p>
        </div>
      )}
    </div>
  )
}